# -*- coding: utf-8 -*-
bytravelSpider={
        'allowedDomains':[
        "bytravel.cn",
        "cn.bytravel.cn",
        "as.bytravel.cn",
        "eur.bytravel.cn",
        "usa.bytravel.cn",
        "ca.bytravel.cn",
        "am.bytravel.cn",
        "aftour.bytravel.cn",
        "au.bytravel.cn",
        "shop.bytravel.cn", #特产
        "guangdong.bytravel.cn",
        "beijing.bytravel.cn", 
        "hongkong.bytravel.cn", 
        "taiwan.bytravel.cn",
    ],
        'startUrls':[
            "http://www.bytravel.cn",
        "http://shop.bytravel.cn/",
        "http://shop.bytravel.cn/tc/"
        ],
        #普通list页正则表达式
        'normalRegex':[                           
            {    
        #如：http://ca.bytravel.cn/
                'regex':'^http://\w+\.bytravel\.cn(/)?$',
                'priority':1000
            },
            {
        #如：http://cn.bytravel.cn/v/index113.html
                'regex':'^/v/index\d+\.html$',
                'priority':1000
            },
            {
        #如：http://cn.bytravel.cn/v/2226/
                'regex':'^/v/\d+/$',
                'priority':1000
            },
            {
        #如：http://ca.bytravel.cn/v/199/7/index.html
                'regex':'^/v/\d+/\d+/index\.html$',
                'priority':1000
            },
            {
        #如：
            #http://cn.bytravel.cn/Scenery/tianjinleyuan110/
            #http://cn.bytravel.cn/Scenery/tjbxs/
                'regex':'^/Scenery/\w+/$',
                'priority':1000
            },
            {
        #特产列表，如：http://shop.bytravel.cn/produce/index138.html
                'regex':'^http://shop\.bytravel\.cn/produce/index\d*\.html$',
                'priority':1000
            },
            {
        #特产列表即分页，如：
            #http://shop.bytravel.cn/produce/index495_list.html
            #http://shop.bytravel.cn/produce/index495_list5.html
                'regex':'^index\d*\_list\d*\.html$',
                'priority':1000
            },       
        {
        #特产列表，如：http://shop.bytravel.cn/tc/Silk.html
                'regex':'^http://shop\.bytravel\.cn/tc/\w+\.html$',
                'priority':1000
            },

        {
        #如：http://beijing.bytravel.cn/Scenery/6/
                'regex':'^/Scenery/\d+/$',
                'priority':1000
            },
        {
        #如：http://taiwan.bytravel.cn/Scenery/Kaohsiung/
                'regex':'^/Scenery/[a-zA-Z]+/$',
                'priority':1000
            },
        {
        #如：http://beijing.bytravel.cn/Scenery/jingdong/list/
                'regex':'^/Scenery/\w+/list/$',
                'priority':1000
            },
        {
        #如：http://beijing.bytravel.cn/Scenery/jingdong/2/
                'regex':'^/Scenery/\w+/\d+/$',
                'priority':1000
            } 
        ],
        #item页正则表达式 itemCollectionName对应item存放的数据表名
        'itemRegex':[
            {
        #如：http://ca.bytravel.cn/art/142/[dt]blhsyt.html
                'itemCollectionName':'Article1',
                'regex':'^/art/\d+/\[dt\]\w+\.html$',
                'priority':1000
            },
        {
        #如：http://usa.bytravel.cn/art/191/jndjd8ry.html
                'itemCollectionName':'Article1',
                'regex':'^/art/\d+/\w+\.html$',
                'priority':1000
            },
        {
        #如：http://ca.bytravel.cn/art/jnd/jndjsymgzjydpfsm/
                'itemCollectionName':'Article1',
                'regex':'^/art/\w+/\w+/$',
                'priority':1000
            },
        {
        #如：http://ca.bytravel.cn/art/[jn/[jnd]hjadlsbwgmzxz/
                'itemCollectionName':'Article1',
                'regex':'^/art/\[\w+/\[\w+\]\w+/$',
                'priority':1000
            },

        {
        #如：http://beijing.bytravel.cn/Scenery/690/bjsshjbj.html
                'itemCollectionName':'Article1',
                'regex':'^/Scenery/\d+/\w+\.html$',
                'priority':1000
            },
        {
        #如：http://beijing.bytravel.cn/Scenery/762/[dt]zhdlbjjjxsdnlgx.html
                'itemCollectionName':'Article1',
                'regex':'^/Scenery/\d+/\[dt\]\w+\.html$',
                'priority':1000
            },

        {
        #特产，如：http://shop.bytravel.cn/produce2/58546CB39A6C9E7F.html
                'itemCollectionName':'Article2',
                'regex':'^/produce2/\w+\.html$',
                'priority':1000
            },
        {
        #特产，如：http://shop.bytravel.cn/produce/9647535759299EBB/
                'itemCollectionName':'Article2',
                'regex':'^/produce/\w+/$',
                'priority':1000
            }    
        ]
    }