# -*- coding: utf-8 -*-
daodaoSpider={
        'allowedDomains':["daodao.com"],
        'startUrls':[
                     #攻略种子页
                        #国内旅游
                        'http://www.daodao.com/Tourism-g297450-c0-Liaoning.html',
                        'http://www.daodao.com/Tourism-g297441-c0-Jiangsu.html',
                        'http://www.daodao.com/Tourism-g297468-c0-Zhejiang.html',
                        'http://www.daodao.com/Tourism-g297455-c0-Shandong.html',
                        'http://www.daodao.com/Tourism-g297411-c0-Guangdong.html',#1
                        'http://www.daodao.com/Tourism-g297436-c0-Hubei.html',
                        'http://www.daodao.com/Tourism-g297462-c0-Sichuan.html',#1
                        'http://www.daodao.com/Tourism-g297460-c0-Shanxi.html',
                        'http://www.daodao.com/Tourism-g303738-c0-Hunan.html',
                        'http://www.daodao.com/Tourism-g297467-c0-Yunnan.html',
                        #直辖市
                        'http://www.daodao.com/Tourism-g294212-c0-Beijing.html',
                        'http://www.daodao.com/Tourism-g308272-c0-Shanghai.html',
                        'http://www.daodao.com/Tourism-g294213-c0-Chongqing.html',#1
                        'http://www.daodao.com/Tourism-g311293-c0-Tianjin.html',
                        #港澳台
                        'http://www.daodao.com/Tourism-g294217-c0-Hong_Kong_Hong_Kong_Region.html',
                        'http://www.daodao.com/Tourism-g664891-c0-Macau_Macau_Region.html',
                        'http://www.daodao.com/Tourism-g293910-c0-Taiwan.html',
                        #65个国外热门国家旅游
                        'http://www.daodao.com/Tourism-g294265-c0-Singapore.html',
                        'http://www.daodao.com/Tourism-g294265-c0-Singapore.html',
                        'http://www.daodao.com/Tourism-g293915-c0-Thailand.html',
                        'http://www.daodao.com/Tourism-g294196-c0-South_Korea.html',
                        'http://www.daodao.com/Tourism-g293921-c0-Vietnam.html',#1
                        'http://www.daodao.com/Tourism-g294443-c0-North_Korea.html',
                        'http://www.daodao.com/Tourism-g293951-c0-Malaysia.html',
                        'http://www.daodao.com/Tourism-g255055-c0-Australia.html',
                        'http://www.daodao.com/Tourism-g293889-c0-Nepal.html',
                        'http://www.daodao.com/Tourism-g191-c0-United_States.html',
                        'http://www.daodao.com/Tourism-g294200-c0-Egypt.html',
                        'http://www.daodao.com/Tourism-g293939-c0-Cambodia.html',
                        'http://www.daodao.com/Tourism-g294245-c0-Philippines.html',
                        'http://www.daodao.com/Tourism-g293740-c0-South_Africa.html',
                        'http://www.daodao.com/Tourism-g293969-c0-Turkey.html',
                        'http://www.daodao.com/Tourism-g186216-c0-United_Kingdom.html',
                        'http://www.daodao.com/Tourism-g187070-c0-France.html',
                        'http://www.daodao.com/Tourism-g294459-c0-Russia.html',
                        'http://www.daodao.com/Tourism-g188045-c0-Switzerland.html',
                        'http://www.daodao.com/Tourism-g294206-c0-Kenya.html',
                        'http://www.daodao.com/Tourism-g293860-c0-India.html',
                        'http://www.daodao.com/Tourism-g187427-c0-Spain.html',
                        'http://www.daodao.com/Tourism-g153339-c0-Canada.html',
                        'http://www.daodao.com/Tourism-g189398-c0-Greece.html',
                        'http://www.daodao.com/Tourism-g255104-c0-New_Zealand.html',
                        'http://www.daodao.com/Tourism-g187275-c0-Germany.html',
                        'http://www.daodao.com/Tourism-g187768-c0-Italy.html',
                        'http://www.daodao.com/Tourism-g294190-c0-Myanmar.html',
                        'http://www.daodao.com/Tourism-g294331-c0-Fiji.html',
                        'http://www.daodao.com/Tourism-g293949-c0-Laos.html',
                        'http://www.daodao.com/Tourism-g190410-c0-Austria.html',
                        'http://www.daodao.com/Tourism-g293977-c0-Israel.html',
                        'http://www.daodao.com/Tourism-g293844-c0-Bhutan.html',
                        'http://www.daodao.com/Tourism-g189952-c0-Iceland.html',
                        'http://www.daodao.com/Tourism-g189806-c0-Sweden.html',
                        'http://www.daodao.com/Tourism-g294473-c0-Ukraine.html',
                        'http://www.daodao.com/Tourism-g188553-c0-The_Netherlands.html',#1
                        'http://www.daodao.com/Tourism-g293961-c0-Sri_Lanka.html',
                        'http://www.daodao.com/Tourism-g293738-c0-Seychelles.html',
                        'http://www.daodao.com/Tourism-g293955-c0-Mongolia.html',
                        'http://www.daodao.com/Tourism-g294280-c0-Brazil.html',
                        'http://www.daodao.com/Tourism-g293730-c0-Morocco.html',
                        'http://www.daodao.com/Tourism-g190455-c0-Norway.html',
                        'http://www.daodao.com/Tourism-g294012-c0-United_Arab_Emirates.html',
                        'http://www.daodao.com/Tourism-g190311-c0-Malta.html',
                        'http://www.daodao.com/Tourism-g274684-c0-Czech_Republic.html',
                        'http://www.daodao.com/Tourism-g294266-c0-Argentina.html',
                        'http://www.daodao.com/Tourism-g189896-c0-Finland.html',
                        'http://www.daodao.com/Tourism-g274881-c0-Hungary.html',
                        'http://www.daodao.com/Tourism-g190405-c0-Monaco.html',
                        'http://www.daodao.com/Tourism-g190340-c0-Luxembourg.html',#1
                        'http://www.daodao.com/Tourism-g189100-c0-Portugal.html',
                        'http://www.daodao.com/Tourism-g294225-c0-Indonesia.html',
                        'http://www.daodao.com/Tourism-g294137-c0-Samoa.html',
                        'http://www.daodao.com/Tourism-g188634-c0-Belgium.html',
                        'http://www.daodao.com/Tourism-g293753-c0-Tunisia.html',
                        'http://www.daodao.com/Tourism-g293747-c0-Tanzania.html',
                        'http://www.daodao.com/Tourism-g293959-c0-Pakistan.html',
                        'http://www.daodao.com/Tourism-g190372-c0-Cyprus.html',#1
                        'http://www.daodao.com/Tourism-g293985-c0-Jordan.html',#1
                        'http://www.daodao.com/Tourism-g293998-c0-Iran.html',
                        'http://www.daodao.com/Tourism-g274960-c0-Latvia.html',
                        'http://www.daodao.com/Tourism-g189512-c0-Denmark.html',
                        'http://www.daodao.com/Tourism-g150768-c0-Mexico.html',
                        'http://www.daodao.com/Tourism-g186591-c0-Ireland.html',
                        'http://www.daodao.com/Tourism-g293953-c0-Maldives.html',
                    #景点种子页
                        'http://www.daodao.com/Attractions-g2-Activities-Asia.html',#亚洲城市景点列表
                        'http://www.daodao.com/Attractions-g4-Activities-Europe.html',#欧洲
                        'http://www.daodao.com/Attractions-g6-Activities-Africa.html',#非洲
                        'http://www.daodao.com/Attractions-g8-Activities-South_Pacific.html',#南太平洋
                        'http://www.daodao.com/Attractions-g13-Activities-South_America.html',#南美洲
                        'http://www.daodao.com/Attractions-g19-Activities-North_America.html',#北美洲
                    #常识种子页（只要热门城市）
                    ], 

        #普通list页正则表达式
        'normalRegex':[
                       #大洲景点列表页的城市
                       {
                        'regex':r'/Attractions-g\d+-Activities-[\w_]+\.html$',
                        'priority':700,
                        'region':'//div[@id="LOCATION_LIST"]',
                        'multitype':False#是否既为list页，也为item页。如果只为list，则不执行item页保存判断
                        },
                       #大洲景点列表页的下一页
                       {
                        'regex':r'/Attractions-g\d+-Activities-oa\d+-[\w_]+\.html$',
                        'priority':800,
                        'region':'//div[@id="LOCATION_LIST"]',
                        'multitype':False#是否既为list页，也为item页。如果只为list，则不执行item页保存判断
                        },
                       #城市景点别表的下一页
                       {
                        'regex':r'/Attractions-g\d+-Activities-[\w_]+\.html$',
                        'priority':850,
                        'region':'//div[@id="ATTRACTION_OVERVIEW"]',
                        'multitype':False#是否既为list页，也为item页。如果只为list，则不执行item页保存判断
                        },
                       
                       #旅游攻略的下一页
                       {
                        'regex':r'Tourism-g\d+-c0-[\w_]+\.html\?pg=\d+$',
                        'priority':100,
                        'region':'//div[@id="result"]/div[1]',
                        'multitype':False#是否既为list页，也为item页。如果只为list，则不执行item页保存判断
                        }
                       ],
        #item页正则表达式 itemCollectionName对应item存放的数据表名
        'itemRegex':[
                     #城市的景点
                     {
                      'itemCollectionName':'Attraction',
                      'regex':r'/Attraction_Review-g\d+-d\d+-Reviews-[\w_]+-[\w_]+\.html$',
                      'priority':1000,
                      'region':'//div[@id="ATTRACTION_OVERVIEW"]',
                      'multitype':False#是否既为list页，也为item页。如果只为list，则不执行item页保存判断
                      },
                     
                     #攻略
                     {
                      'itemCollectionName':'Article',
                      'regex':r'Tourism-g\d+[-\w\d_]+[\w\d_]+\.html$',
                      'priority':1000,
                      'region':'//div[@id="result"]/div[2]',
                      'multitype':False#是否既为list页，也为item页。如果只为list，则不执行item页保存判断
                      },
                     ]
    }