# -*- coding: utf-8 -*-
jinghuaSpider={
                     'allowedDomains':[
                                       "www.lvping.com",
                                       "www.go2eu.com",
                                       "www.17u.com",
                                       "bbs.55bbs.com",
                                       ],
                     'startUrls':[
                                  'http://www.lvping.com/Journals.aspx?type=1&pageindex=1', 
                                  'http://www.lvping.com/Journals.aspx?type=2&pageindex=1', #lvping
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=53&filter=digest&page=1', #穷游精选 美国
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=112&filter=digest&page=1', #穷游精选 欧洲
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=14&filter=digest&page=1',#穷游精选 法国
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=12&filter=digest&page=1',#德国
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=13&filter=digest&page=1',#意大利
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=17&filter=digest&page=1',#荷兰比利时
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=16&filter=digest&page=1',#英国
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=19&filter=digest&page=1',#奥地利
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=18&filter=digest&page=1',#西班牙
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=15&filter=digest&page=1',#瑞士
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=26&filter=digest&page=1',#希腊
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=58&filter=digest&page=1',#亚洲各国
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=57&filter=digest&page=1',#日本韩国
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=106&filter=digest&page=1',#泰国
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=108&filter=digest&page=1',#新马泰
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=107&filter=digest&page=1',#柬埔寨
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=110&filter=digest&page=1',#菲律宾
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=111&filter=digest&page=1',#印尼
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=103&filter=digest&page=1',#印度
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=102&filter=digest&page=1',#尼泊尔
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=104&filter=digest&page=1',#马尔代夫
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=52&filter=digest&page=1',#香港
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=51&filter=digest&page=1',#国内
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=53&filter=digest&page=1',#美国
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=54&filter=digest&page=1',#加拿大
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=55&filter=digest&page=1',#拉美
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=56&filter=digest&page=1',#澳大利亚
                                  'http://www.go2eu.com/bbs/forumdisplay.php?fid=83&filter=digest&page=1',#新西兰
                                  'http://www.17u.com/blog/best/1',#17u.com
                                  'http://bbs.55bbs.com/forumdisplay.php?fid=34&filter=digest&page=1',#55bbs
                                  ],
                     #普通list页正则表达式
                     'normalRegex':[
                                    #lvping
                                    {
                                     'regex':r'/Journals\.aspx\?type=[12]+&title=&district=0&IsTitle=T&selecttype=0&orderby=[rd]+&pageindex=\d+$', 
                                     'region':'//form[@id="newMasterForm"]/div[5]/div[2]/div[3]/div[3]',
                                     'priority':1,
                                     },
                                    #go2eu
                                    {
                                     'regex':r'forumdisplay\.php\?fid=\d+&filter=digest&page=\d+$',
                                     'region':'//body/div[6]/div[4]/div',
                                     'priority':1, 
                                     },
                                    #17u
                                    {
                                     'regex':r'/blog/best/\d+$',
                                     'region':'//div[@id="pageList"]/div',
                                     'priority':1, 
                                     },
                                    #55bbs
                                    {
                                     'regex':r'forumdisplay\.php\?fid=34&filter=digest&page=\d+$', 
                                     'region':'//div[@id="list_left"]/div[1]/div[1]',
                                     'priority':1,
                                     },
                                    ],
                     #item页正则表达式 itemCollectionName对应item存放的数据表名
                     'itemRegex':[
                                  #lvping
                                  {
                                   'itemCollectionName':'Article',
                                   'regex':r'(/showjournal\-d\d+-r\d+\-journals\.html)|(/journals/AllSingleJournals\.aspx\?Writing=\d+)|(travel\-d\d+\-s\d+/\w+:\w+\.html)|(/showjournal\-d\w+\-r\d+\-detail\.html)',
                                   'region':'//div[@id="yjDetail"]',
                                   'priority':1000
                                   },
                                  #go2eu
                                  {
                                   'itemCollectionName':'BBSArticle',
                                   'regex':r'viewthread\.php\?tid=\d+&extra=page[(=)|(%3D)]+\d+[(&)|(%26)]+amp[(;)|(%3B)]+filter[(=)|(%3D)]+digest$',
                                   'region':'//div/form/table',
                                   'priority':1000
                                   },
                                  #17u
                                  {
                                   'itemCollectionName':'BBSArticle',
                                   'regex':r'/blog/article/\d+\.html$',
                                   'region':'//div[@id="major"]/table',
                                   'priority':1000
                                   },
                                  #55bbs
                                  {
                                   'itemCollectionName':'BBSArticle',
                                   'regex':r'thread-\d+-1-\d+\.html$',
                                   'region':'//div/form/table',
                                   'priority':1000
                                   },
                                  ]
                     }