# -*- coding: utf-8 -*-
lvrenSpider={
        'allowedDomains':["d.lvren.cn"],
        'startUrls':[ 
        'http://d.lvren.cn/guide/',
        'http://d.lvren.cn/china/',
        'http://d.lvren.cn/world/',
        'http://news.lvren.cn/html/lvyouzixun/',
        'http://news.lvren.cn/html/gedilvyou/',
        'http://news.lvren.cn/html/huwaipindao/',
        'http://news.lvren.cn/html/jiudianpindao/',
        'http://news.lvren.cn/html/xianluyouji/'
        ],
        #普通list页正则表达式
        'normalRegex':[
            {
        #列表：分页
        'regex':r'^list_\d+_\d+.html$',
                'priority':1000
            },
        {
        #如：http://d.lvren.cn/guide/scenic_48173/
                'regex':r'^/guide/\w+/$', 
        'priority':1000
            },

        {
        #获取包含游记的页面，如：http://d.lvren.cn/lvyou/yunnandali/
                'regex':r'^/lvyou/\w+/$', 
        'priority':1000
            },
        {
        #获取游记列表，如：http://d.lvren.cn/youji/yunnandali/
                'regex':r'^/youji/\w+/$', 
        'priority':1000
            },
            {
        #获取游记列表：分页页面，如：http://d.lvren.cn/youji/yunnandali_p2/
                'regex':r'^/youji/\w+_p\d+/$', 
                'priority':1000
            }        
       ],
        #item页正则表达式 itemCollectionName对应item存放的数据表名
        'itemRegex':[
            #Article 文章
        {
        #旅游资讯，如：http://news.lvren.cn/html/lvyouzixun/201109/2748492.html
                'itemCollectionName':'Article1',
         'regex':r'^/html/lvyouzixun/\d+/\d+(_\d+)?\.html$',
                'priority':600
            },
        {
        #旅游资讯，如：
            #各地美食：http://news.lvren.cn/html/lvyouzixun/gedimeishi/201108/3048286.html
            #旅游天气：http://news.lvren.cn/html/lvyouzixun/weather/201012/2146395.html
            #出境旅游：http://news.lvren.cn/html/lvyouzixun/chujinglvyou/201109/2148450.html
            #旅游新闻：http://news.lvren.cn/html/lvyouzixun/news/201109/2848500.html
                'itemCollectionName':'Article1',
         'regex':r'^/html/lvyouzixun/[a-zA-Z]+/\d+/\d+(_\d+)?\.html$',
                'priority':600
            },
            {
        #各地旅游，如：http://news.lvren.cn/html/gedilvyou/beijinglvyou/201106/2847832.html
                'itemCollectionName':'Article1',
         'regex':r'^/html/gedilvyou/[a-zA-Z]+/\d+/\d+(_\d+)?\.html$',
                'priority':600
            },
        {
        #各地旅游，如：http://news.lvren.cn/html/lvyou//201011/3046220.html
                'itemCollectionName':'Article1',
         'regex':r'^/html/lvyou//\d+/\d+(_\d+)?\.html$',
                'priority':600
            },
         {
        #户外频道，如：http://news.lvren.cn/html/huwaixinwen/2010/0322/41560.html
                'itemCollectionName':'Article1',
         'regex':r'^/html/huwaixinwen/\d+/\d+/\d+(_\d+)?\.html$',
                'priority':600
            },
        {
        #户外频道，如：http://news.lvren.cn/html/huwaipindao/hangyebaodao/2010/0316/41525.html
                'itemCollectionName':'Article1',
         'regex':r'^/html/huwaipindao/[a-zA-Z]+/\d+/\d+/\d+(_\d+)?\.html$',
                'priority':600
            },
        {
        #酒店频道，如：http://news.lvren.cn/html/jiudianpindao/201001/1537815.html
                'itemCollectionName':'Article1',
         'regex':r'^/html/jiudianpindao/\d+/\d+(_\d+)?\.html$',
                'priority':600
            },
        {
        #线路游记，如：http://news.lvren.cn/html/xianluyouji/2010/0222/41105.html
                'itemCollectionName':'Article1',
         'regex':r'^/html/xianluyouji/\d+/\d+/\d+(_\d+)?\.html$',
                'priority':600
            },
        {
        #线路游记，如：http://news.lvren.cn/html/xianluyouji/beijinglvyougonglue/2010/0223/41188.html
                'itemCollectionName':'Article1',
         'regex':r'^/html/xianluyouji/[a-zA-Z]+/\d+/\d+/\d+(_\d+)?\.html$',
                'priority':600
            },
        {
        #游人攻略，如：http://d.lvren.cn/gonglue/dongjing/
                'itemCollectionName':'Article2',
                'regex':r'^/gonglue/\w+/$',
                'priority':600
            }, 
        {
        #游记文章，如：http://d.lvren.cn/youji/yunnandali_100930/
                'itemCollectionName':'Article3',
                'regex':r'/youji/\w+_\d+/',
                'priority':600
            }
        ]
    }