# -*- coding: utf-8 -*-
mafengwoSpider={
        'allowedDomains':["www.mafengwo.cn"],
        'startUrls':[                            
            "http://www.mafengwo.cn",
        'http://www.mafengwo.cn/s/sitemap.html',
        'http://www.mafengwo.cn/mdd/info_list.php',
        'http://www.mafengwo.cn/mdd/travel_list.php',
        ],
        #普通list页正则表达式
        'normalRegex':[    
            {
        #国内外攻略，如：http://www.mafengwo.cn/travel-scenic-spot/mafengwo/11780.html
                'regex':'^/travel-scenic-spot/mafengwo/\d+\.html$',
                'priority':1000
            },
        {
        #国内外攻略分页，如：http://www.mafengwo.cn/mdd/detail.php?mddid=10184&sort=&start=135
                'regex':'^/mdd/detail\.php\?mddid=\d+&sort=&start=\d+$',
                'priority':1000
        },        
        {
        #最新游记列表及分页，如：
            #http://www.mafengwo.cn/mdd/info_list.php
            #http://www.mafengwo.cn/mdd/info_list.php?start=1200
                'regex':'^/mdd/info_list\.php(\?start=\d+)?$',
                'priority':1000
        },
        {
        #资讯列表及分页，如：
            #http://www.mafengwo.cn/mdd/travel_list.php
            #http://www.mafengwo.cn/mdd/travel_list.php?from_time=&type=&start=200
                'regex':'^/mdd/travel_list\.php(\?from_time=&type=&start=\d+)?$',
                'priority':1000
            }
        ],
        #item页正则表达式 itemCollectionName对应item存放的数据表名
        'itemRegex':[
            {
        #文章，如：http://www.mafengwo.cn/i/741413.html
                'itemCollectionName':'Article',
                'regex':'^http://www\.mafengwo\.cn/i/\d+\.html$',
                'priority':600
            }, 
        {
        #文章，如：http://www.mafengwo.cn/i/751314.html
                'itemCollectionName':'Article',
                'regex':'^/i/\d+\.html$',
                'priority':600
            }, 
        {
        #资讯文章，如：http://www.mafengwo.cn/travel-news/188417.html 
                'itemCollectionName':'Article',
                'regex':'^/travel-news/\d+\.html$',
                'priority':600
            },
        ]
    }