# -*- coding: utf-8 -*-
onegreenSpider={
                     'allowedDomains':[
                                       "www.onegreen.net",
                                       ],
                     'startUrls':[
                                  'http://www.onegreen.net/maps/List/List_711.html',
                                  'http://www.onegreen.net/maps/List/List_1167.html',
                                  'http://www.onegreen.net/maps/List/List_712.html',
                                  'http://www.onegreen.net/maps/List/List_747.html',
                                  'http://www.onegreen.net/maps/List/List_748.html',
                                  'http://www.onegreen.net/maps/List/List_749.html',
                                  'http://www.onegreen.net/maps/List/List_750.html',
                                  'http://www.onegreen.net/maps/List/List_751.html',
                                  'http://www.onegreen.net/maps/List/List_752.html',
                                  'http://www.onegreen.net/maps/List/List_753.html',
                                  'http://www.onegreen.net/maps/List/List_754.html',
                                  'http://www.onegreen.net/maps/List/List_755.html',
                                  'http://www.onegreen.net/maps/List/List_756.html',
                                  'http://www.onegreen.net/maps/List/List_757.html',
                                  'http://www.onegreen.net/maps/List/List_758.html',
                                  'http://www.onegreen.net/maps/List/List_759.html',
                                  'http://www.onegreen.net/maps/List/List_760.html',
                                  'http://www.onegreen.net/maps/List/List_761.html',
                                  'http://www.onegreen.net/maps/List/List_762.html',
                                  'http://www.onegreen.net/maps/List/List_763.html',
                                  'http://www.onegreen.net/maps/List/List_764.html',
                                  'http://www.onegreen.net/maps/List/List_765.html',
                                  'http://www.onegreen.net/maps/List/List_766.html',
                                  'http://www.onegreen.net/maps/List/List_767.html',
                                  'http://www.onegreen.net/maps/List/List_768.html',
                                  'http://www.onegreen.net/maps/List/List_769.html',
                                  'http://www.onegreen.net/maps/List/List_770.html',
                                  'http://www.onegreen.net/maps/List/List_771.html',
                                  'http://www.onegreen.net/maps/List/List_772.html',
#                                  'http://www.onegreen.net/maps/List/List_1177.html',#交通图
                                  ],
                     #普通list页正则表达式
                     'normalRegex':[
                                    {
                                     'regex':r'/maps/ShowClass\.asp\?ClassID=\d+&page=\d+$',
                                     'region':'//table[1]//table//tr[2]/td/div',
                                     'priority':1,
                                     },
                                    ],
                     #item页正则表达式 itemCollectionName对应item存放的数据表名
                     'itemRegex':[
                                  {
                                   'itemCollectionName':'ImageItem',
                                   'regex':r'/maps/HTML/\d+\.html$',
                                   'region':'//table[1]//table//tr[2]/td/table',
                                   'priority':1000
                                   },
                                  ]
                     }